name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file buildenv/Dockerfile --tag megaos-env

    - name: Compile kernel
      run: cd kernel && docker run --rm -v ${{ github.workspace }}:/env megaos-env make build-x86_64

    - name: Uploade build ISO file
      uses: actions/upload-artifact@v4
      with:
        name: MegaOS-Build
        path: dist/x86_64/kernel.iso
